# Runs this repo's action against the current PR so we validate the action works
# with the commit we're directly using. Upload step requires TRUNK_TOKEN secret.
name: Test Action (Self)
on:
  pull_request:

permissions: read-all

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run the action on this commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run merge-action (this repo)
        uses: .
        with:
          trunk-token: NOT_NEEDED
          bazel-workspace-path: ./tests/bazel8
          verbose: "false"
