# Runs this repo's action against the current PR so we validate the action works
# with the commit we're directly using. Upload step requires TRUNK_TOKEN secret.
name: Test Action (Self)
on: pull_request

permissions: read-all

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run the action on this commit
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get checked-out ref
        id: get-ref
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Run merge-action (this repo)
        uses: trunk-io/merge-action@${{ steps.get-ref.outputs.sha }}
        with:
          trunk-token: NOT_NEEDED
          bazel-workspace-path: ./tests/bazel8
          verbose: "false"
